### ISSUE TITLE
Блок выбора диапазона

### ISSUE THREAD

**Issue by Morfey216** [lizalukyanenko/Nerds#10]
В HTML по умолчанию нет элемента для двухдиапазонного выбора значений. Ты пытаешься реализовать одиночный бегунок http://joxi.ru/Rmz4JpxTRabL4A
https://github.com/lizamarmysh/Nerds/blob/2de0521ab0e62767ce0346a46372b094aafae187/catalog.html#L33-L36

Данный блок реализуется так:
```
<div class="skroll">
  <div class="range__block">
	<div class="range__bar"></div>
	<button class="skroll__min"></button>
	<button class="skroll__max"></button>
  </div>
</div>
```

Далее этот код обрабатывается JavaScript-ом (в текущем проекте реализовывать не обязательно)

**Comment by lizalukyanenko** [comment]
Изменила на данный блок
