### ISSUE TITLE
Чекбоксы и радиобаттоны

### ISSUE THREAD

**Issue by Morfey216** [lizalukyanenko/Nerds#12]
Эти блоки кода работать не будут
https://github.com/lizamarmysh/Nerds/blob/2de0521ab0e62767ce0346a46372b094aafae187/catalog.html#L48-L61
https://github.com/lizamarmysh/Nerds/blob/2de0521ab0e62767ce0346a46372b094aafae187/catalog.html#L65-L86

Не веришь? 
Тогда вопрос: подскажи, какая из сеток выбрана?
https://github.com/lizamarmysh/Nerds/blob/2de0521ab0e62767ce0346a46372b094aafae187/catalog.html#L55

Или что здесь отмечено: слайдер, новости или галерея?
https://github.com/lizamarmysh/Nerds/blob/2de0521ab0e62767ce0346a46372b094aafae187/catalog.html#L76

Тут важно помнить, что id-шник НЕ является данными, которые уходят из формы на сервер

Тем более, что здесь можно протестировать:
Выбираем http://joxi.ru/Grq4nOXTkZM99A
Отправляем форму и получаем http://joxi.ru/EA4Py7zTOVREwA

**Comment by lizalukyanenko** [comment]
Верю, забыла value. Исправила
