### ISSUE TITLE
Классы-модификаторы

### ISSUE THREAD

**Issue by Morfey216** [lizalukyanenko/Nerds#14]
В случае применения класса, каким-либо образом меняющего базовый класс, правильнее было бы отразить базовый класс в названии, т.е. классы в строке
https://github.com/lizamarmysh/Nerds/blob/cd2c12e5a1432ee7d0909b6d73b361a1c928c1eb/index.html#L35

заменить на `class="button button-red"`

ну и в стилях класс-модификатор прописать рядом с родительским, после него, чтобы не искать по всему коду

P.S. А вообще для решения подобной задачи придумали специальные технологии (методики), мы с ними познакомимся на следующем проекте

**Comment by lizalukyanenko** [comment]
исправила
