### ISSUE TITLE
Параметры текста

### ISSUE THREAD

**Issue by Morfey216** [lizalukyanenko/Nerds#15]
Мне кажется, что "косяк" в стилизации виден невооруженным глазом: http://joxi.ru/L21PxnzTgd9xWm

А вся проблема в макете: макеты от дизайнеров чаще всего приходят далёкими от идеала. Так и здесь: высота строки прописана заведомо меньше размера шрифта
https://github.com/lizamarmysh/Nerds/blob/cf52df0dafe1b2558b33ee9c8df30169aab8f7b4/css/style.css#L218-L219

На будущее - чтобы избежать проблем с отображением текста (чтобы строки не наплывали одна на другую), высота строки желательна не меньше, чем размер шрифта.

**Comment by lizalukyanenko** [comment]
исправила
