### ISSUE TITLE
Элементы управления

### ISSUE THREAD

**Issue by Morfey216** [lizalukyanenko/Nerds#16]
Здесь должны быть кнопки
https://github.com/lizamarmysh/Nerds/blob/cf52df0dafe1b2558b33ee9c8df30169aab8f7b4/index.html#L49-L50

**Comment by lizalukyanenko** [comment]
понял. принял

**Comment by Morfey216** [comment]
Ну, кнопки ты сделала, а вот про доступность забыла
https://github.com/lizamarmysh/Nerds/blob/ce31206c15ea3bfbe048c0b416345313ce55856e/index.html#L49-L50

**Comment by lizalukyanenko** [comment]
ready
