### ISSUE TITLE
Разметка контактов (телефонов)

### ISSUE THREAD

**Issue by Morfey216** [lizalukyanenko/Nerds#2]
С точки зрения разметки номеров телефонов, адресов электронной почты и т.п. - эти данные размечаются ссылками
https://github.com/lizamarmysh/Nerds/blob/0a55032fb63ef3a663f2dd6e932e7056049e50d5/index.html#L143-L145

Подробнее - в примерах https://developer.mozilla.org/ru/docs/Web/HTML/Element/A

**Comment by lizalukyanenko** [comment]
ready

**Comment by Morfey216** [comment]
Скобки в адресе ссылки лучше убрать
https://github.com/lizamarmysh/Nerds/blob/f45310f244f7b1906e362c7991d420a9923b86ae/index.html#L138

**Comment by lizalukyanenko** [comment]
ok
