### ISSUE TITLE
Вложенность селекторов

### ISSUE THREAD

**Issue by Morfey216** [lizalukyanenko/Nerds#21]
Зачем такие сложности с вложенностью селекторов?
https://github.com/lizamarmysh/Nerds/blob/ce31206c15ea3bfbe048c0b416345313ce55856e/css/style.css#L206

Смотрим разметку:
https://github.com/lizamarmysh/Nerds/blob/ce31206c15ea3bfbe048c0b416345313ce55856e/index.html#L84-L96

т.е. 
1. между корневым классом `about-us` и элементом списка у тебя вагон кода и отслеживать такую вложенность не очень приятно
2. у элемента списка есть собственный класс и правильнее использовать для стилизации именно его 
https://github.com/lizamarmysh/Nerds/blob/ce31206c15ea3bfbe048c0b416345313ce55856e/index.html#L91

`.order-item::before {...}`
в таком виде код становится простым, легко читаемым и логически понятным

3. Как думаешь, что будет со стилизацией, если клиент переместит блок со списком в другую часть сайта, "выдернув" его из секции `about-us` ? Нужно добиваться максимальной устойчивости кода.

**Comment by lizalukyanenko** [comment]
Отлично, это то, что мне нужно было! Постоянно сомневалась какой уровень вложенности лучше использовать
