### ISSUE TITLE
Адреса ссылок

### ISSUE THREAD

**Issue by Morfey216** [lizalukyanenko/Nerds#4]
1. Не совсем понятно, почему у разных товаров одинаковые адреса
2. Если адрес не известен, лучше использовать заглушку `#`
https://github.com/lizamarmysh/Nerds/blob/0a55032fb63ef3a663f2dd6e932e7056049e50d5/catalog.html#L51
https://github.com/lizamarmysh/Nerds/blob/0a55032fb63ef3a663f2dd6e932e7056049e50d5/catalog.html#L59

и далее по коду...

**Comment by lizalukyanenko** [comment]
ready
