### ISSUE TITLE
Контентные изображения

### ISSUE THREAD

**Issue by Morfey216** [lizalukyanenko/Nerds#6]
Данные изображения нужно добавить в разметку
http://joxi.ru/Vm6P8qxTjMjeZA

**Comment by lizalukyanenko** [comment]
Не считаю это логичным решением, ведь изображения не несут никакой информативности и являются фоновыми. При их отсутствии контент страницы бы не пострадал. 
Вопрос принят. Задача выполнена.

**Comment by Morfey216** [comment]
В таких случаях, как этот, могут возникать спорные моменты. Например, картинки на следующем скрине несут декоративную функцию, тем не менее они добавлены в разметку. Подумай на досуге, почему...
http://joxi.ru/52aPNgJibLR5Om

Другими словами - декоративные изображения _могут_ быть в разметке

**Comment by lizalukyanenko** [comment]
Возможно потому, что визуализация контента быстрее воспринимается пользователями, нежели текст.
