### ISSUE TITLE
Ошибки в разметке

### ISSUE THREAD

**Issue by Morfey216** [lizalukyanenko/Nerds#7]
Не совсем понятно, для чего в разметке эти элементы:
https://github.com/lizamarmysh/Nerds/blob/2de0521ab0e62767ce0346a46372b094aafae187/index.html#L35-L36

Если это заготовки для реализации слайдера, то это делается не так. В любом случае - **внутри** слайдов этих элементов быть не должно

**Comment by lizalukyanenko** [comment]
Ок. На данном этапе их просто убрать? Или чем-то заменить?

**Comment by Morfey216** [comment]
Этот код нужно убрать не зависимо от этапа, в таком виде код не будет работать.

> Или чем-то заменить?

Нужен другой подход к реализации блока управления слайдами.
В принципе, есть два основных способа работы со слайдами: со скриптами и без скриптов. В нынешнее время управление переключением слайдов чаще реализуют при помощи JavaScript - этот способ достаточно простой и очень гибкий. Попробуй пока поискать сама, вопросы по ходу дела можешь задавать в телеграм

**Comment by lizalukyanenko** [comment]
ок

**Comment by Morfey216** [comment]
Для начала можно просто разместить блок пагинации, сразу после списка со слайдами.
```
<div class="slider-pagination">
	<div class="pagination-bullet"></div>
	<div class="pagination-bullet"></div>
	<div class="pagination-bullet"></div>
	<div class="pagination-bullet"></div>
</div>
```

тебе останется его правильно стилизовать

**Comment by lizalukyanenko** [comment]
Так и сделала

**Comment by Morfey216** [comment]
Так, да не так...
https://github.com/lizamarmysh/Nerds/blob/cd2c12e5a1432ee7d0909b6d73b361a1c928c1eb/index.html#L51-L55

1. Что в этом коде делает нижнее подчеркивание? Нарушен критерий Б15.
2. У слайдеров есть "навигация" и "пагинация" - это специальные, устоявшиеся блоки управления переключением слайдов. Лучше использовать правильный нейминг, дабы не вводить людей в заблуждение

**Comment by lizalukyanenko** [comment]
испраила
