### ISSUE TITLE
Валидация

### ISSUE THREAD

**Issue by Morfey216** [lizalukyanenko/Nerds#9]
Ошибки валидации недопустимы
http://joxi.ru/vAWPRzViqppGer

А здесь можно ознакомиться с причиной https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/multiple

**Comment by lizamarmysh** [comment]
Пока не понимаю, как сделать 2 ползунка в input range

**Comment by lizalukyanenko** [comment]
ready

**Comment by Morfey216** [comment]
И снова валидация:
Страница каталога: http://joxi.ru/J2b8PMVtGZ0aZr
Стили: http://joxi.ru/Y2LJPgYCQp7lLr

**Comment by lizalukyanenko** [comment]
ready
